- hosts: localhost
  connection: local
  remote_user: root
  sudo: yes
  
  tasks:
  - name: Install WEB packages
  # Apacheとmod_sslをインストール。
    yum: name="{{ item }}" state=present
    with_items:
    - httpd
    - mod_ssl

  - name: Install php5.4 packages
  # PHP5.4をインストール。
    yum: name="{{ item }}" state=present
    with_items:
      - php
      - php-mbstring
      - php-pdo
      - php-mysql
      - php-xml
      - php-gd
      - php-ldap
      - php-process
      
  - name: Install DataBase packages
  # MariaDBをインストール。
    yum: name="{{ item }}" state=present
    with_items:
      - mariadb-server
      - mariadb
      - mariadb-libs
      - MySQL-python

  - name: service restart
  # ApacheとDBの再起動
    service: name=""{{ item }]" state=restarted enabled=yes
    with_items:
      - httpd
      - mariadb
  

